services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-nerdstore-management
    restart: unless-stopped
    ports: 
      - 15672:15672  
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"

  sql-server:
    image: dnalves/nerdstore-sql-server:latest
    container_name: nerdstore-sql-server
    restart: unless-stopped
    ports:
      - 1433:1433
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    environment:
        SA_PASSWORD: "MeuDB@123"
        ACCEPT_EULA: "Y"

  web-mvc:
    image: dnalves/nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc-ecommerce
    ports:
      - 5000:5000
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5000
    depends_on:
      - rabbitmq
      - api-catalogo
      - api-identidade
      - api-clientes
      - api-bff-compras

  api-identidade:
    image: dnalves/nerdstore-api-identidade:latest
    container_name: nerdstore-api-identidade
    restart: unless-stopped
    build:
      context: ../src
      dockerfile: ./services/NSE.Identidade.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5100
    depends_on:
      - rabbitmq
      - sql-server

  api-catalogo:
    image: dnalves/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    restart: unless-stopped
    build:
      context: ../src
      dockerfile: ./services/NSE.Catalogo.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5200
    depends_on:
      - rabbitmq
      - sql-server

  api-clientes:
    image: dnalves/nerdstore-api-clientes:latest
    container_name: nerdstore-api-clientes
    restart: unless-stopped
    build:
      context: ../src
      dockerfile: ./services/NSE.Clientes.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5300
    depends_on:
      - rabbitmq
      - sql-server
      - api-identidade

  api-carrinho:
    image: dnalves/nerdstore-api-carrinho:latest
    container_name: nerdstore-api-carrinho
    restart: unless-stopped
    build:
      context: ../src
      dockerfile: ./services/NSE.Carrinho.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5400
    depends_on:
      - rabbitmq
      - sql-server
      - api-identidade

  api-pedidos:
    image: dnalves/nerdstore-api-pedidos:latest
    container_name: nerdstore-api-pedidos
    restart: unless-stopped
    build:
      context: ../src
      dockerfile: ./services/NSE.Pedidos.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5500
    depends_on:
      - rabbitmq
      - sql-server
      - api-identidade

  api-pagamentos:
    image: dnalves/nerdstore-api-pagamentos:latest
    container_name: nerdstore-api-pagamentos
    restart: unless-stopped
    build:
      context: ../src
      dockerfile: ./services/NSE.Pagamentos.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5600
    depends_on:
      - rabbitmq
      - sql-server
      - api-identidade
      - api-pedidos

  api-bff-compras:
    image: dnalves/nerdstore-api-bff-compras:latest
    container_name: nerdstore-api-bff-compras
    restart: unless-stopped
    build:
      context: ../src
      dockerfile: ./api-gateways/NSE.Bff.Compras/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5700
    depends_on:
      - rabbitmq
      - api-catalogo
      - api-identidade
      - api-pedidos
      - api-carrinho
      - api-pagamentos